# Generated by Django 2.2.5 on 2019-09-14 22:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0002_document_user_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='user_id',
            new_name='user',
        ),
    ]
