# Generated by Django 2.2.5 on 2019-09-14 23:12

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0004_result_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='result',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2019, 9, 14, 23, 12, 7, 877726, tzinfo=utc), verbose_name='Date of update'),
        ),
    ]
