# Generated by Django 2.2.5 on 2019-09-14 23:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0005_auto_20190914_2312'),
    ]

    operations = [
        migrations.AlterField(
            model_name='result',
            name='date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Date of update'),
        ),
    ]
